version: '3.8'

services:
  backend:
    build:
      context: ./back
    ports:
      - "5001:5001"
    environment:
      - HUGGINGFACE_API_TOKEN
    restart: unless-stopped

  frontend:
    build:
      context: ./front
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
